version: "3.7"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: flash-ptsp-app
    container_name: flash-ptsp-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - flash-ptsp-network

  nginx:
    image: nginx:alpine
    container_name: flash-ptsp-nginx
    restart: unless-stopped
    ports:
      - "8090:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d/
    networks:
      - flash-ptsp-network

  db:
    image: mysql:8.0
    container_name: flash-ptsp-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: flash_kemenag
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
      MYSQL_USER: flash
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    networks:
      - flash-ptsp-network

  redis:
    image: redis:alpine
    container_name: flash-ptsp-redis
    restart: unless-stopped
    networks:
      - flash-ptsp-network

networks:
  flash-ptsp-network:
    driver: bridge
